spring:
  application:
    name: ftgo-courier-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/ftgo_courier}
    username: ${SPRING_DATASOURCE_USERNAME:ftgo_user}
    password: ${DB_PASSWORD:ftgo_password}
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: ${SERVER_PORT:8084}
