server.host: "0.0.0.0"
server.name: "ftgo-kibana"
elasticsearch.hosts: ["http://elasticsearch:9200"]
monitoring.ui.container.elasticsearch.enabled: true
xpack.fleet.enabled: false
telemetry.optIn: false
telemetry.allowChangingOptInStatus: false
