apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: ftgo-tracing
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/part-of: ftgo
    app.kubernetes.io/component: tracing
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: jaeger
  ports:
    - name: zipkin
      port: 9411
      targetPort: 9411
      protocol: TCP
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
    - name: collector-http
      port: 14268
      targetPort: 14268
      protocol: TCP
    - name: model-proto
      port: 14250
      targetPort: 14250
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: ftgo-tracing
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/part-of: ftgo
    app.kubernetes.io/component: tracing
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: jaeger
  ports:
    - name: query-http
      port: 16686
      targetPort: 16686
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  namespace: ftgo-tracing
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/part-of: ftgo
    app.kubernetes.io/component: tracing
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: jaeger
  ports:
    - name: agent-compact
      port: 6831
      targetPort: 6831
      protocol: UDP
    - name: agent-binary
      port: 6832
      targetPort: 6832
      protocol: UDP
    - name: agent-config
      port: 5778
      targetPort: 5778
      protocol: TCP
