dependencies {
    api project(":common-swagger")
    api project(":ftgo-consumer-service-api")
    api project(":ftgo-domain")

    api "org.springframework.boot:spring-boot-starter-data-jpa"
    api "org.springframework.boot:spring-boot-starter-web"
    api "org.springframework.boot:spring-boot-starter-actuator"

    testImplementation "org.springframework.boot:spring-boot-starter-test"
    testImplementation "io.rest-assured:rest-assured"
    testImplementation "com.jayway.jsonpath:json-path"
}
