apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: ftgo-monitoring
  labels:
    app: prometheus
    app.kubernetes.io/part-of: ftgo
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: http
  selector:
    app: prometheus
