apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/tracing

# Staging overrides: in-memory storage, moderate resources
patches:
  - target:
      kind: ConfigMap
      name: zipkin-config
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: zipkin-config
      data:
        storage-type: "mem"
        java-opts: "-Xms256m -Xmx512m"
