apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: consumer-service-pdb
  labels:
    app.kubernetes.io/name: consumer-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: consumer-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: courier-service-pdb
  labels:
    app.kubernetes.io/name: courier-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: courier-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: order-service-pdb
  labels:
    app.kubernetes.io/name: order-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: order-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: restaurant-service-pdb
  labels:
    app.kubernetes.io/name: restaurant-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: restaurant-service
