package net.chrisrichardson.ftgo.common.tracking;

final class ApiTrackingExamples {

  static final String LOG_RESPONSE = "{\n"
          + "  \"id\": 7,\n"
          + "  \"correlationId\": \"bd7e0ee1-175e-4ddb-8c52-a2d07a04ce6a\",\n"
          + "  \"httpMethod\": \"GET\",\n"
          + "  \"requestUri\": \"/orders/1\",\n"
          + "  \"queryString\": null,\n"
          + "  \"responseStatus\": 200,\n"
          + "  \"durationMs\": 10,\n"
          + "  \"remoteAddr\": \"127.0.0.1\",\n"
          + "  \"userAgent\": \"curl/7.81.0\",\n"
          + "  \"errorMessage\": null,\n"
          + "  \"requestTimestamp\": \"2026-09-29T15:30:51\"\n"
          + "}";

  static final String LOGS_RESPONSE = "[\n"
          + "  {\n"
          + "    \"id\": 20,\n"
          + "    \"correlationId\": \"f07b3a4d-1bfe-42b6-ac70-31fe8ffc26c7\",\n"
          + "    \"httpMethod\": \"GET\",\n"
          + "    \"requestUri\": \"/orders\",\n"
          + "    \"queryString\": \"consumerId=1\",\n"
          + "    \"responseStatus\": 200,\n"
          + "    \"durationMs\": 14,\n"
          + "    \"remoteAddr\": \"127.0.0.1\",\n"
          + "    \"userAgent\": \"curl/7.81.0\",\n"
          + "    \"errorMessage\": null,\n"
          + "    \"requestTimestamp\": \"2026-09-29T15:30:52\"\n"
          + "  },\n"
          + "  {\n"
          + "    \"id\": 7,\n"
          + "    \"correlationId\": \"bd7e0ee1-175e-4ddb-8c52-a2d07a04ce6a\",\n"
          + "    \"httpMethod\": \"GET\",\n"
          + "    \"requestUri\": \"/orders/1\",\n"
          + "    \"queryString\": null,\n"
          + "    \"responseStatus\": 200,\n"
          + "    \"durationMs\": 10,\n"
          + "    \"remoteAddr\": \"127.0.0.1\",\n"
          + "    \"userAgent\": \"curl/7.81.0\",\n"
          + "    \"errorMessage\": null,\n"
          + "    \"requestTimestamp\": \"2026-09-29T15:30:51\"\n"
          + "  }\n"
          + "]";

  static final String ERROR_LOGS_RESPONSE = "[\n"
          + "  {\n"
          + "    \"id\": 20,\n"
          + "    \"correlationId\": \"f07b3a4d-1bfe-42b6-ac70-31fe8ffc26c7\",\n"
          + "    \"httpMethod\": \"GET\",\n"
          + "    \"requestUri\": \"/orders\",\n"
          + "    \"queryString\": \"consumerId=1\",\n"
          + "    \"responseStatus\": 200,\n"
          + "    \"durationMs\": 14,\n"
          + "    \"remoteAddr\": \"127.0.0.1\",\n"
          + "    \"userAgent\": \"curl/7.81.0\",\n"
          + "    \"errorMessage\": null,\n"
          + "    \"requestTimestamp\": \"2026-09-29T15:30:52\"\n"
          + "  },\n"
          + "  {\n"
          + "    \"id\": 7,\n"
          + "    \"correlationId\": \"bd7e0ee1-175e-4ddb-8c52-a2d07a04ce6a\",\n"
          + "    \"httpMethod\": \"GET\",\n"
          + "    \"requestUri\": \"/orders/1\",\n"
          + "    \"queryString\": null,\n"
          + "    \"responseStatus\": 200,\n"
          + "    \"durationMs\": 10,\n"
          + "    \"remoteAddr\": \"127.0.0.1\",\n"
          + "    \"userAgent\": \"curl/7.81.0\",\n"
          + "    \"errorMessage\": null,\n"
          + "    \"requestTimestamp\": \"2026-09-29T15:30:51\"\n"
          + "  }\n"
          + "]";

  static final String STATS_RESPONSE = "{\n"
          + "  \"totalRequests\": 20,\n"
          + "  \"periodMinutes\": 60,\n"
          + "  \"errorCount\": 4,\n"
          + "  \"errorRate\": 0.2,\n"
          + "  \"avgDurationMs\": 24.85,\n"
          + "  \"p95DurationMs\": 299,\n"
          + "  \"statusCodeDistribution\": {\n"
          + "    \"200\": 16,\n"
          + "    \"404\": 1,\n"
          + "    \"409\": 1,\n"
          + "    \"500\": 2\n"
          + "  },\n"
          + "  \"topEndpoints\": {\n"
          + "    \"POST /orders\": 2,\n"
          + "    \"GET /orders/1\": 2,\n"
          + "    \"POST /orders/1/accept\": 1,\n"
          + "    \"POST /orders/1/cancel\": 1,\n"
          + "    \"GET /couriers/1\": 1\n"
          + "  }\n"
          + "}";

  private ApiTrackingExamples() {
  }
}
