# FTGO Platform - Production Environment Overlay
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ftgo-platform-prod

namespace: ftgo-prod

# resources:
#   - ../../base

commonLabels:
  environment: production
