apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: ftgo-logging
  labels:
    app.kubernetes.io/name: kibana
    app.kubernetes.io/part-of: ftgo
    app.kubernetes.io/component: logging
data:
  kibana.yml: |
    server.name: ftgo-kibana
    server.host: "0.0.0.0"
    server.port: 5601
    elasticsearch.hosts: ["http://elasticsearch.ftgo-logging.svc.cluster.local:9200"]
    elasticsearch.requestTimeout: 30000
    logging.root.level: info
    telemetry.optIn: false
    telemetry.allowChangingOptInStatus: false
