apiVersion: v1
kind: Service
metadata:
  name: ftgo-mysql
  labels:
    app.kubernetes.io/name: ftgo-mysql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: ftgo
spec:
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql
  clusterIP: None
  selector:
    app.kubernetes.io/name: ftgo-mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ftgo-mysql
  labels:
    app.kubernetes.io/name: ftgo-mysql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: ftgo
spec:
  serviceName: "ftgo-mysql"
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ftgo-mysql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ftgo-mysql
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: ftgo
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: ftgo-mysql
          image: msapatterns/mysql:latest
          imagePullPolicy: Always
          args:
            - "--ignore-db-dir=lost+found"
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ftgo-db-secret
                  key: root-password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: ftgo-db-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ftgo-db-secret
                  key: password
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          volumeMounts:
            - name: ftgo-mysql-persistent-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: ftgo-mysql-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
