apiVersion: v1
kind: ConfigMap
metadata:
  name: ftgo-template-service-config
  labels:
    app: ftgo-template-service
    part-of: ftgo
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8080"
  SPRING_DATASOURCE_URL: "jdbc:mysql://ftgo-mysql:3306/ftgo_template"
  SPRING_DATASOURCE_USERNAME: "ftgo_user"
