apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  namespace: ftgo-tracing
  labels:
    app: zipkin
    app.kubernetes.io/name: zipkin
    app.kubernetes.io/part-of: ftgo
    app.kubernetes.io/component: tracing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
        app.kubernetes.io/name: zipkin
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin:2.24
          ports:
            - containerPort: 9411
              name: http
              protocol: TCP
          env:
            - name: STORAGE_TYPE
              value: "mem"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 9411
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 9411
            initialDelaySeconds: 30
            periodSeconds: 15
