spring.application.name=ftgo-application

spring.jpa.generate-ddl=false
logging.level.org.springframework.orm.jpa=INFO
logging.level.org.hibernate.SQL=DEBUG
spring.datasource.url=jdbc:mysql://${DOCKER_HOST_IP:localhost}/ftgo?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=mysqluser
spring.datasource.password=mysqlpw
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

ftgo.sla.default-threshold-minutes=30
ftgo.sla.state-threshold-minutes.APPROVED=10
ftgo.sla.state-threshold-minutes.ACCEPTED=15
ftgo.sla.state-threshold-minutes.PREPARING=30
ftgo.sla.state-threshold-minutes.READY_FOR_PICKUP=15
ftgo.sla.state-threshold-minutes.PICKED_UP=45
