spring.sleuth.enabled=${SPRING_SLEUTH_ENABLED:true}
spring.sleuth.sampler.probability=${SPRING_SLEUTH_SAMPLER_PROBABILITY:1.0}
spring.zipkin.base-url=${SPRING_ZIPKIN_BASE_URL:http://localhost:9411/}
spring.zipkin.enabled=${SPRING_ZIPKIN_ENABLED:true}

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.metrics.export.prometheus.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.tags.application=${spring.application.name}
