apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ftgo-staging

commonLabels:
  environment: staging

resources:
  - ../../base
  - namespace.yaml

patches:
  # Staging uses 2 replicas (same as base)
  - target:
      kind: HorizontalPodAutoscaler
    patch: |
      - op: replace
        path: /spec/minReplicas
        value: 2
      - op: replace
        path: /spec/maxReplicas
        value: 5

configMapGenerator:
  - name: ftgo-env-config
    literals:
      - ENVIRONMENT=staging
      - LOG_LEVEL=INFO
