apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ftgo-dev

namePrefix: dev-

labels:
  - pairs:
      app.kubernetes.io/environment: dev
    includeSelectors: false

commonAnnotations:
  environment: dev

resources:
  - ../../base
  - namespace.yaml

patches:
  - path: patches/replicas.yaml
  - path: patches/resource-limits.yaml

configMapGenerator:
  - name: consumer-service-config
    literals:
      - SPRING_PROFILES_ACTIVE=kubernetes,dev
      - LOGGING_LEVEL_ROOT=DEBUG
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,metrics,prometheus,env
  - name: courier-service-config
    literals:
      - SPRING_PROFILES_ACTIVE=kubernetes,dev
      - LOGGING_LEVEL_ROOT=DEBUG
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,metrics,prometheus,env
  - name: order-service-config
    literals:
      - SPRING_PROFILES_ACTIVE=kubernetes,dev
      - LOGGING_LEVEL_ROOT=DEBUG
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,metrics,prometheus,env
  - name: restaurant-service-config
    literals:
      - SPRING_PROFILES_ACTIVE=kubernetes,dev
      - LOGGING_LEVEL_ROOT=DEBUG
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,metrics,prometheus,env
