dependencies {
    // TODO eliminate this - problem is value objects like Money need to be embeddable.
    // TODO https://en.wikibooks.org/wiki/Java_Persistence/Embeddables#Example_of_an_Embeddable_object_XML

    compile "org.springframework.boot:spring-boot-starter-data-jpa:$springBootVersion"
    compile "org.springframework.boot:spring-boot-starter-web:$springBootVersion"

    compile group: 'com.fasterxml.jackson.core', name: 'jackson-core', version: '2.9.7'
    compile group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.9.7'
    compile group: 'commons-lang', name: 'commons-lang', version: '2.6'
    compile "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.9.7"

    compile 'mysql:mysql-connector-java:8.0.33'

    testCompile "org.springframework.boot:spring-boot-starter-test:$springBootVersion"

    // JAXB and JAF are no longer bundled with the JDK starting with Java 11
    // (JEP 320), so they are provided explicitly. The 2.3.x line is the
    // reference implementation that runs cleanly on Java 11.
    runtime "javax.xml.bind:jaxb-api:2.3.1"
    runtime "org.glassfish.jaxb:jaxb-runtime:2.3.1"
    runtime "javax.activation:javax.activation-api:1.2.0"
}
