---
apiVersion: v1
kind: Namespace
metadata:
  name: ftgo-dev
  labels:
    app.kubernetes.io/part-of: ftgo
    environment: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: ftgo-staging
  labels:
    app.kubernetes.io/part-of: ftgo
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: ftgo-prod
  labels:
    app.kubernetes.io/part-of: ftgo
    environment: prod
