apiVersion: v1
kind: Service
metadata:
  name: consumer-service
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: consumer-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-service
  template:
    metadata:
      labels:
        app: consumer-service
    spec:
      containers:
      - name: consumer-service
        image: ftgo-consumer-service:latest
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://consumer-mysql:3306/ftgo_consumer
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: consumer-mysql-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: consumer-mysql-secret
              key: password
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: com.mysql.jdbc.Driver
        - name: JAVA_OPTS
          value: -Xmx192m
