apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: order-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: ftgo-order-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://order-mysql:3306/ftgo_order
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: order-mysql-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: order-mysql-secret
              key: password
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: com.mysql.jdbc.Driver
        - name: CONSUMER_SERVICE_HOST
          value: consumer-service
        - name: RESTAURANT_SERVICE_HOST
          value: restaurant-service
        - name: COURIER_SERVICE_HOST
          value: courier-service
        - name: JAVA_OPTS
          value: -Xmx192m
