apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
spec:
  ports:
  - port: 8082
    targetPort: 8082
  selector:
    app: restaurant-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-service
  template:
    metadata:
      labels:
        app: restaurant-service
    spec:
      containers:
      - name: restaurant-service
        image: ftgo-restaurant-service:latest
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://restaurant-mysql:3306/ftgo_restaurant
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: restaurant-mysql-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: restaurant-mysql-secret
              key: password
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: com.mysql.jdbc.Driver
        - name: JAVA_OPTS
          value: -Xmx192m
