apiVersion: v1
kind: Service
metadata:
  name: restaurant-mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: restaurant-mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: restaurant-mysql
spec:
  serviceName: restaurant-mysql
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-mysql
  template:
    metadata:
      labels:
        app: restaurant-mysql
    spec:
      containers:
      - name: restaurant-mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: root-password
        - name: MYSQL_DATABASE
          value: ftgo_restaurant
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: mysql-password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: restaurant-mysql-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: restaurant-mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
