spring.application.name=order-service

spring.jpa.generate-ddl=false
logging.level.org.springframework.orm.jpa=INFO
logging.level.org.hibernate.SQL=DEBUG
spring.datasource.url=jdbc:mysql://${DOCKER_HOST_IP:localhost}/ftgo_order?useSSL=false
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.jdbc.Driver

spring.flyway.enabled=true

server.port=8080

consumer.service.url=http://${CONSUMER_SERVICE_HOST:localhost}:8081
restaurant.service.url=http://${RESTAURANT_SERVICE_HOST:localhost}:8082
courier.service.url=http://${COURIER_SERVICE_HOST:localhost}:8083
