spring.application.name=order-service
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/ftgo_order
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:mysqluser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
flyway.enabled=true

consumer.service.url=http://localhost:8083
restaurant.service.url=http://localhost:8082
courier.service.url=http://localhost:8084
