apply plugin: FtgoServicePlugin
apply plugin: IntegrationTestsPlugin

configurations {
    integrationTestCompile.setExtendsFrom([compile])
    integrationTestRuntime.setExtendsFrom([integrationTestCompile, runtime])
}

sourceSets {
    integrationTest {
        compileClasspath = sourceSets.main.output + configurations.integrationTestCompile
        runtimeClasspath = output + compileClasspath + configurations.integrationTestRuntime
    }
}

integrationTest {
    classpath = files(sourceSets.integrationTest.output, sourceSets.main.output) +
            configurations.integrationTestRuntime
}

dependencies {
    compile project(":ftgo-consumer-service")
    compile project(":ftgo-order-service-client")
    compile project(":ftgo-restaurant-service")
    compile project(":ftgo-courier-service")

    compile "org.springframework.boot:spring-boot-starter-actuator:$springBootVersion"
    compile "org.springframework.boot:spring-boot-starter-web:$springBootVersion"

    runtime 'mysql:mysql-connector-java:8.0.33'

    testCompile project(":ftgo-end-to-end-tests-common")

    integrationTestCompile "org.springframework.boot:spring-boot-starter-test:$springBootVersion"
    integrationTestCompile project(":ftgo-order-service")
    integrationTestRuntime "com.h2database:h2:1.4.197"
}