apply plugin: FtgoServicePlugin

dependencies {
    api project(":ftgo-consumer-service")
    api project(":ftgo-order-service")
    api project(":ftgo-restaurant-service")
    api project(":ftgo-courier-service")

    api "org.springframework.boot:spring-boot-starter-actuator"
    api "org.springframework.boot:spring-boot-starter-web"

    // Version managed by the Spring Boot BOM.
    runtimeOnly "com.mysql:mysql-connector-j"

    testImplementation project(":ftgo-end-to-end-tests-common")
}