apiVersion: v1
kind: Secret
metadata:
  name: ftgo-db-secret
  labels:
    app: ftgo-mysql
    part-of: ftgo
    tier: database
type: Opaque
stringData:
  root-password: "REPLACE_WITH_ACTUAL_VALUE"
  username: "REPLACE_WITH_ACTUAL_VALUE"
  password: "REPLACE_WITH_ACTUAL_VALUE"
