apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: ftgo-logging
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/part-of: ftgo
    app.kubernetes.io/component: logging
data:
  elasticsearch.yml: |
    cluster.name: ftgo-logs
    node.name: ${HOSTNAME}
    network.host: 0.0.0.0
    http.port: 9200
    transport.port: 9300
    discovery.type: single-node
    path.data: /usr/share/elasticsearch/data
    path.logs: /usr/share/elasticsearch/logs
    bootstrap.memory_lock: false
    xpack.security.enabled: false
    xpack.ilm.enabled: true
    http.cors.enabled: true
    http.cors.allow-origin: "*"
    http.cors.allow-headers: "X-Requested-With,Content-Type,Content-Length,Authorization"
