apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
    part-of: ftgo
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      targetPort: http
      protocol: TCP
  selector:
    app: order-service
