{{- if .Values.namespaceCreate }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    {{- include "ftgo.labels" (dict "name" "ftgo-platform" "context" $) | nindent 4 }}
{{- end }}
