spring:
  application:
    name: consumer-service
  datasource:
    url: jdbc:mysql://${DOCKER_HOST_IP:localhost}/ftgo_consumer?useSSL=false&createDatabaseIfNotExist=true
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8081

logging:
  level:
    org.springframework.orm.jpa: INFO
    org.hibernate.SQL: DEBUG
