apiVersion: v1
kind: Secret
metadata:
  name: restaurant-service-secrets
  labels:
    app: restaurant-service
    part-of: ftgo
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "REPLACE_WITH_ACTUAL_VALUE"
  SPRING_DATASOURCE_PASSWORD: "REPLACE_WITH_ACTUAL_VALUE"
