CREATE DATABASE IF NOT EXISTS ftgo;
GRANT ALL PRIVILEGES ON ftgo.* TO 'mysqluser'@'%' WITH GRANT OPTION;

CREATE DATABASE IF NOT EXISTS ftgo_consumer;
GRANT ALL PRIVILEGES ON ftgo_consumer.* TO 'mysqluser'@'%' WITH GRANT OPTION;
