buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.flywaydb:flyway-mysql:10.17.3"
        classpath "com.mysql:mysql-connector-j:${mysqlConnectorVersion}"
    }
}

plugins {
    id "org.flywaydb.flyway" version "10.17.3"
}

flyway {
    url = "jdbc:mysql://${System.getenv('DOCKER_HOST_IP') ?: 'localhost'}/ftgo?useSSL=false&allowPublicKeyRetrieval=true"
    user = 'root'
    password = 'rootpassword'
    schemas = ['ftgo']
}
