apiVersion: v1
kind: ConfigMap
metadata:
  name: ftgo-courier-service-config
  labels:
    app: ftgo-courier-service
    part-of: ftgo
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8084"
  SPRING_DATASOURCE_URL: "jdbc:mysql://ftgo-mysql:3306/ftgo_courier"
  SPRING_DATASOURCE_USERNAME: "ftgo_user"
