apiVersion: v1
kind: Service
metadata:
  name: ftgo-courier-service
  labels:
    app: ftgo-courier-service
    part-of: ftgo
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8084
      protocol: TCP
      name: http
  selector:
    app: ftgo-courier-service
