apiVersion: v1
kind: ConfigMap
metadata:
  name: ftgo-consumer-service-config
  labels:
    app: ftgo-consumer-service
    part-of: ftgo
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8081"
  SPRING_DATASOURCE_URL: "jdbc:mysql://ftgo-mysql:3306/ftgo_consumer"
  SPRING_DATASOURCE_USERNAME: "ftgo_user"
