apiVersion: v1
kind: ConfigMap
metadata:
  name: ftgo-restaurant-service-config
  labels:
    app: ftgo-restaurant-service
    part-of: ftgo
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8083"
  SPRING_DATASOURCE_URL: "jdbc:mysql://ftgo-mysql:3306/ftgo_restaurant"
  SPRING_DATASOURCE_USERNAME: "ftgo_user"
