apiVersion: v1
kind: Service
metadata:
  name: courier-service
  labels:
    app: courier-service
    part-of: ftgo
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8084
      targetPort: http
      protocol: TCP
  selector:
    app: courier-service
