apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ftgo.app.fullname" . }}
  labels:
    {{- include "ftgo.app.labels" . | nindent 4 }}
data:
  SPRING_DATASOURCE_URL: {{ include "ftgo.datasourceUrl" . | quote }}
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
  JAVA_OPTS: {{ .Values.app.javaOpts | quote }}
  {{- range $k, $v := .Values.app.extraConfig }}
  {{ $k }}: {{ $v | toString | quote }}
  {{- end }}
